/**
 * AI Summary Card Component
 * Displays the AI-generated audit summary
 */

import { Sparkles, AlertCircle } from "lucide-react";

interface AISummaryCardProps {
  summary: string;
  isAIGenerated: boolean;
}

export function AISummaryCard({
  summary,
  isAIGenerated,
}: AISummaryCardProps) {
  return (
    <div className="rounded-lg border border-border bg-card p-6 shadow-sm">
      <div className="flex items-start justify-between mb-4">
        <div className="flex items-center gap-2">
          <div className="rounded-lg bg-gradient-to-br from-purple-500 to-blue-500 p-2">
            <Sparkles className="h-5 w-5 text-white" />
          </div>
          <div>
            <h3 className="font-semibold text-foreground">AI Audit Summary</h3>
            {!isAIGenerated && (
              <p className="text-xs text-muted-foreground flex items-center gap-1 mt-1">
                <AlertCircle className="h-3 w-3" />
                Template-based summary
              </p>
            )}
          </div>
        </div>
      </div>

      <p className="text-sm leading-relaxed text-foreground/90">
        {summary}
      </p>

      {isAIGenerated && (
        <p className="text-xs text-muted-foreground mt-4 pt-4 border-t border-border">
          ✨ Generated by AI for your unique spending patterns
        </p>
      )}
    </div>
  );
}
